name: Release

on:
  push:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set manifest version number
        run: |
          python ${{ github.workspace }}/.github/update_manifest.py --version ${{ github.ref_name }}
      - name: Create zip
        run: |
          cd custom_components/epg
          zip epg.zip -r ./
      - name: Test
        run: pwd
      - name: test2
        run: ls -lR
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/epg/hacs.json
          asset_name: epg.zip
          tag: ${{ github.ref }}
          overwrite: true
